spring:
  main:
    web-application-type: reactive # 以响应式方式运行Web应用，防止与MVC冲突
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用服务名进行路由
          lower-case-service-id: true # 用小写的请求路径的服务名匹配服务，默认为false
      routes:
        - id: baiduroute
          uri: https://www.baidu.com
          predicates:
            - Path=/baidu/**
        - id: ticket-service
          uri: lb://ticket-service # 指定URI，集成负载均衡机制
          predicates:
            - Path=/ticket/** # 指定谓词，当请求URL中包含 /ticket/**时会被 自动转发到ticket-service
          filters:
            - StripPrefix=1
        - id: chat-service
          uri: lb://chat-service # 指定URI，集成负载均衡机制
          predicates:
            - Path=/chat/** # 指定谓词，当请求URL中包含 /chat/**时会被 自动转发到chat-service
          filters:
            - StripPrefix=1
            - PrefixPath=/chats # 指定过滤器