server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    #超时时间
    connection-timeout: 60000ms
    #最小线程数
    min-spare-threads: 100
    #最大线程数
    max-threads: 800
    #最大连接数
    max-connections: 10000
    #最大等待队列长度
    accept-count: 500
  undertow:
    io-threads: 4 #设置IO线程数
    worker-threads: 20 #设置工作线程数
    buffer-size: 1024 #设置buffer大小
    direct-buffers: true # 是否分配的直接内存
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.249.130:8848
        namespace: dae2f8c4-a44a-4143-afc5-1f8aaa84c72c
        group: LCL_GALAXY_GROUP
        cluster-name: beijing
  application:
    name: middleground-task

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

xxl:
  job:
    accessToken: lcl-token
    executor:
      appname: customer-system
      ip:
      logpath: /Users/conglongli/Documents/workspace/customer-system/customer-system-monolith/logs
      logretentiondays: -1
      port: 9999
    admin:
      addresses: http://localhost:8888/xxl-job-admin
