server:
  port: 9004

spring:
  application:
    name: chat-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.249.130:8848
        namespace: dae2f8c4-a44a-4143-afc5-1f8aaa84c72c
        group: LCL_GALAXY_GROUP
        cluster-name: beijing
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  datasource:
    dynamic:
      primary: master
      druid:
        initial-size: 3
        min-idle: 3
        max-active: 40
        max-wait: 60000
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/chat_at?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: is_deleted
      # 逻辑删除字面值：未删除为0
      logic-not-delete-value: 0
      # 逻辑删除字面值：删除为1
      logic-delete-value: 1

seata:
  enable-auto-data-source-proxy: true # 必须设置为 true，默认为true
  application-id: ${spring.application.name}
  tx-service-group: chat-service-group
  service:
    vgroup-mapping:
      business-service-group: beijing
  #    grouplist:
  #      default: 127.0.0.1:8091
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.249.130:8848
      application: seata-server
      group: SEATA_GROUP
      namespace: dae2f8c4-a44a-4143-afc5-1f8aaa84c72c
  config:
    type: nacos
    nacos:
      server-addr: 192.168.249.130:8848
      group: SEATA_GROUP
      namespace: dae2f8c4-a44a-4143-afc5-1f8aaa84c72c