server:
  port: 8003
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  

spring:
  application:
    name: intergation-service


logging:
    level:
      com.lcl.projects.cs: INFO

