server:
  port: 8003
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  

spring:
  application:
    name: intergation-service
  profiles:
    active: @spring.profiles.active@
  cloud:
    nacos:
      discovery:
        server-addr: @spring.cloud.nacos.discovery.server-addr@
        enabled: true
        cluster-name: beijing
        group: LCL_GALAXY_GROUP
        namespace:  @spring.cloud.nacos.discovery.namespace@
#    config:
#      server-addr: 192.168.249.130:8848

logging:
    level:
      com.lcl.projects.cs: INFO

