GET localhost:9004/chatRecords/
Accept: application/json

###
GET localhost:9004/chatRecords/123
Accept: application/json

###
POST localhost:9004/chatRecords/
Content-Type: application/json

{
  "userId" : "100",
  "staffId" : "202",
  "inquire" : "你好，测试",
  "ticketNo" : "ticketNo1"
}

###
GET localhost:9004/chatRecords/switch
Accept: application/json