GET http://localhost:9004/chats/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzeXN0ZW0iOiJteV9jc19zeXN0ZW0iLCJ1c2VyX25hbWUiOiJ1c2VyMiIsInNjb3BlIjpbIndlYmNsaWVudCJdLCJleHAiOjE2OTEzNzM0NDgsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiOTE1ZDkzMWEtOTc3ZS00NDVjLTkxNjUtNWMzZjQyODdmODcwIiwiY2xpZW50X2lkIjoiY3NfY2xpZW50In0.l_NQOWcYQdHlZd0EHBxKZ_ksO9Kj565cQjMn9Z8UO9k

###
